### ISSUE TITLE
Dislplay: flex

### ISSUE THREAD

**Issue by ghost** [Treppord/your-tribe-squad-page#5]
Wat is flex(box): https://css-tricks.com/snippets/css/a-guide-to-flexbox/
Leren met flexbox: https://flexboxfroggy.com/#nl

Die flexbox froggy is een leuke manier om flexbox te leren, je begint best snel het idee te krijgen van wat het is en hoe het werkt.

**Comment by Treppord** [comment]
Leuke tip, thx man!
